// AUTO-GENERATED by _build_nextjs_data.py.
// Scroll-scene camera keyframes, captions, and per-car material overrides.

export type SceneKeyframe = [progress: number, orbit: string];
export type SceneCaption = {
  from: number;
  to: number;
  pos: "left" | "right" | "bottom";
  eyebrow: string;
  line: string;
};
export type MaterialOverride = {
  /** Case-insensitive regex source matched against material.name. */
  match: string;
  /** RGBA in 0..1 linear space. */
  color: [number, number, number, number];
  metallic?: number;
  roughness?: number;
};
export type DoorRig = {
  /** Case-insensitive regex matching door node names. */
  match: string;
  /** Axis of rotation on the hinge pivot. */
  axis: "x" | "y" | "z";
  /** Which face of the door bounding box to treat as the hinge edge. */
  hingeOn: "xmin" | "xmax" | "ymin" | "ymax" | "zmin" | "zmax";
  /** Rotation at progress=1, in radians. */
  maxRadians: number;
  /** Scroll progress at which the door starts opening. */
  startProgress: number;
};
export type SceneConfig = {
  /** No longer consumed at runtime — camera is driven by per-slug presets in
   *  src/lib/cameraPresets.ts. Field stays optional so the auto-generated
   *  build script doesn't need a parallel patch. */
  keyframes?: SceneKeyframe[];
  captions: SceneCaption[];
  finaleTitle: string;
  materialOverrides?: MaterialOverride[];
  doorRig?: DoorRig;
};

export const scenesBySlug: Record<string, SceneConfig> = {
  "countach": {
    keyframes: [
      [0.0, "25deg 78deg 105%"],
      [0.18, "80deg 84deg 92%"],
      [0.38, "170deg 82deg 110%"],
      [0.58, "265deg 78deg 95%"],
      [0.8, "325deg 72deg 70%"],
      [1.0, "340deg 74deg 40%"],
    ],
    captions: [
      { from: 0.03, to: 0.22, pos: "left", eyebrow: "Gallery I, 1970s", line: "Designed in 1971. Still the shape people draw when they imagine a supercar." },
      { from: 0.22, to: 0.45, pos: "right", eyebrow: "The rear wing", line: "That rear wing? Bolted on in a parking lot. With a hand drill." },
      { from: 0.45, to: 0.68, pos: "bottom", eyebrow: "No wind tunnel", line: "Never saw the inside of a wind tunnel. Engineers used fabric strips and a camera." },
      { from: 0.68, to: 0.78, pos: "right", eyebrow: "16 years in production", line: "Every revision added wings. Every one moved further from the original." },
    ],
    finaleTitle: "The scissor door opens onto the 1980s.",
    // Door rig removed — the GLB's pivot for SK_Door_FL rotates the
    // scissor door DOWNWARD instead of up, which reads as broken.
    // Re-enable once the GLB hinge axis is fixed in Blender.
    // White materialOverride removed — kept the GLB's baked red paint.
  },
  "959": {
    keyframes: [
      [0.0, "20deg 82deg 108%"],
      [0.22, "80deg 92deg 82%"],
      [0.45, "160deg 80deg 110%"],
      [0.68, "225deg 75deg 95%"],
      [0.88, "320deg 80deg 58%"],
      [1.0, "335deg 78deg 32%"],
    ],
    captions: [
      { from: 0.03, to: 0.22, pos: "left", eyebrow: "PSK all-wheel drive", line: "All-wheel drive with four modes. In 1986. Before anyone else asked for it." },
      { from: 0.22, to: 0.45, pos: "bottom", eyebrow: "Sequential turbocharging", line: "Two turbos, working in sequence. No lag. No compromise." },
      { from: 0.45, to: 0.68, pos: "right", eyebrow: "Two dampers per corner", line: "One for stiffness. One for height. Both automatic." },
      { from: 0.68, to: 0.78, pos: "left", eyebrow: "292 built", line: "Every one lost Porsche money. Every one rewrote the rulebook." },
    ],
    finaleTitle: "From Weissach to Woking. The 1990s are waiting.",
    materialOverrides: [
      { match: "body|paint|lack|carrosserie|exterior|shell|karosserie", color: [0.55, 0.012, 0.016, 1.0], metallic: 0.85, roughness: 0.28 },
    ],
  },
  "f1": {
    keyframes: [
      [0.0, "40deg 88deg 115%"],
      [0.22, "110deg 82deg 95%"],
      [0.45, "190deg 85deg 105%"],
      [0.68, "260deg 78deg 95%"],
      [0.88, "30deg 68deg 55%"],
      [1.0, "25deg 60deg 28%"],
    ],
    captions: [
      { from: 0.03, to: 0.22, pos: "left", eyebrow: "Central driving position", line: "The driver sits in the center. Not left, not right. The center." },
      { from: 0.22, to: 0.45, pos: "right", eyebrow: "Carbon monocoque", line: "Carbon fiber body, gold-lined engine bay. Every gram was argued over." },
      { from: 0.45, to: 0.68, pos: "bottom", eyebrow: "627 horsepower", line: "No traction control. Murray said you didn't need it." },
      { from: 0.68, to: 0.78, pos: "left", eyebrow: "391 km/h", line: "1998. No production car touched it for twelve years." },
    ],
    finaleTitle: "Analog perfection hands off to the digital thousand.",
    materialOverrides: [
      { match: "tail|taillight|rear.?light|brake.?light|rearlamp|lamp.*rear", color: [0.36, 0.005, 0.005, 1.0], metallic: 0.0, roughness: 0.35 },
    ],
  },
  "veyron": {
    keyframes: [
      [0.0, "15deg 82deg 112%"],
      [0.22, "90deg 90deg 85%"],
      [0.45, "180deg 82deg 115%"],
      [0.68, "215deg 72deg 85%"],
      [0.88, "325deg 78deg 55%"],
      [1.0, "335deg 74deg 30%"],
    ],
    captions: [
      { from: 0.03, to: 0.22, pos: "left", eyebrow: "W16 engine", line: "Two V8s on one crankshaft. 16 cylinders. Four turbochargers. One road car." },
      { from: 0.22, to: 0.45, pos: "right", eyebrow: "1,000 horsepower", line: "The engineers said it was impossible. Piech disagreed." },
      { from: 0.45, to: 0.68, pos: "bottom", eyebrow: "Autocar, 2014", line: "220 mph in 30 seconds. The only car Autocar ever measured to that speed." },
      { from: 0.68, to: 0.78, pos: "left", eyebrow: "1,900 kg", line: "It handles like a normal car. That is the most impressive part." },
    ],
    finaleTitle: "1,001 horsepower. The decade closes at 253 mph.",
    doorRig: {
      match: "doorLF",
      axis: "y",
      hingeOn: "zmax",
      maxRadians: 1.1,
      startProgress: 0.86,
    },
  },
};
