/**
 * Single source of truth for editable site content.
 *
 * Each row describes ONE editable string:
 *   sheet  — Excel sheet it lives on
 *   page   — Column A (which page/section it belongs to)
 *   field  — Column B (human label, e.g. "Hero stat")
 *   value  — Column C (current text in the source file)
 *   file   — relative path of the source file to update
 *
 * The export script (export_content.ts) writes this to site_content.xlsx.
 * The import script (import_content.ts) reads the xlsx, finds rows with
 * a non-empty NEW VALUE column, and rewrites the matching `value` in the
 * `file` referenced here.
 *
 * NOTE on auto-generated files:
 *   - src/lib/scenes.ts and src/lib/artifacts.ts are AUTO-GENERATED by
 *     the Python build pipeline (_build_nextjs_data.py). Editing them
 *     directly works but the next regeneration will wipe your changes.
 *     We deliberately exclude scene captions / artifact captions from
 *     this export — edit them at the source (Markdown / Python).
 */

import { cars } from "../src/lib/cars.js";
import { scenesBySlug } from "../src/lib/scenes.js";
import { artifactsBySlug } from "../src/lib/artifacts.js";
import { bibliography } from "../src/lib/bibliography.js";

export type ContentRow = {
  sheet: string;
  page: string;
  field: string;
  value: string;
  file: string;
};

const REL = (p: string) => p.replace(/^\//, "");

/** Hand-curated rows for nav/footer/homepage/about/global metadata. */
const STATIC_ROWS: ContentRow[] = [
  // ========= NAVIGATION =========
  { sheet: "Navigation", page: "Header", field: "Site name (header)", value: "The Motor Gallery", file: REL("src/components/SiteHeader.tsx") },
  { sheet: "Navigation", page: "Header", field: "About link label",   value: "About",             file: REL("src/components/SiteHeader.tsx") },
  { sheet: "Navigation", page: "Header", field: "Established badge",  value: "Est. 2026",         file: REL("src/components/SiteHeader.tsx") },

  { sheet: "Navigation", page: "Footer", field: "Site name (footer)",       value: "The Motor Gallery",                                                                      file: REL("src/components/SiteFooter.tsx") },
  { sheet: "Navigation", page: "Footer", field: "Footer description",       value: "A small curation of the automobiles that rewrote their decades — told in\n            photographs, engineering notes, and quiet reverence.", file: REL("src/components/SiteFooter.tsx") },
  { sheet: "Navigation", page: "Footer", field: "Footer column 1 heading",  value: "Exhibits",                                                                                file: REL("src/components/SiteFooter.tsx") },
  { sheet: "Navigation", page: "Footer", field: "Footer column 2 heading",  value: "Gallery",                                                                                 file: REL("src/components/SiteFooter.tsx") },
  { sheet: "Navigation", page: "Footer", field: "Footer link: About",       value: "About the curation",                                                                      file: REL("src/components/SiteFooter.tsx") },
  { sheet: "Navigation", page: "Footer", field: "Footer link: Visit",       value: "Visit · by appointment",                                                                  file: REL("src/components/SiteFooter.tsx") },
  { sheet: "Navigation", page: "Footer", field: "Footer link: Press",       value: "Press · inquire",                                                                         file: REL("src/components/SiteFooter.tsx") },
  { sheet: "Navigation", page: "Footer", field: "Footer copyright tagline", value: "Cars Throughout The Decades",                                                             file: REL("src/components/SiteFooter.tsx") },

  // ========= ABOUT =========
  { sheet: "About", page: "About",        field: "Eyebrow",           value: "About the gallery",                                              file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Headline",          value: "A small gallery for the automobiles that mattered.",            file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Curation eyebrow",  value: "Curation",                                                       file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Curation lede",     value: "Four machines, one per decade, chosen because each one forced the rest of\n              the industry to answer a new question.", file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Body 1 (pull)",     value: "The automobile is the twentieth century&apos;s most looked-at sculpture.", file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Body 2",            value: "We treat it that way. Each exhibit presents a single car in the way a\n              museum would present a single canvas: a long look, a few careful words,\n              the room quiet enough to hear the engineering.", file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Body 3",            value: "The collection is deliberately small. A larger survey would obscure the\n              argument. Four cars over four decades, the Countach, the 959, the\n              McLaren F1, the Veyron, tell the whole story of what the supercar\n              became, and why.", file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Body 4",            value: "Photography, essays, and three-dimensional studies are produced in-house.\n              Technical data is drawn from contemporary press kits and manufacturer\n              homologation documents. When a detail is disputed, we say so.", file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Hours label",       value: "Hours",                                                          file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Hours value",       value: "By appointment",                                                 file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Location label",    value: "Location",                                                       file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Location value",    value: "Digital, for now",                                               file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Correspondence label", value: "Correspondence",                                              file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Correspondence value", value: "Always welcome",                                              file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Bibliography eyebrow", value: "Bibliography",                                                 file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Bibliography heading", value: "Primary-source artifacts cited across the four galleries.",   file: REL("src/app/about/page.tsx") },
  { sheet: "About", page: "About",        field: "Bibliography lede", value: "Every image and text deduplicated and alphabetized by author. Chicago style.", file: REL("src/app/about/page.tsx") },

  // ========= GLOBAL (SEO/metadata) =========
  { sheet: "Global", page: "Layout",      field: "SEO title",          value: "The Motor Gallery — Cars Throughout The Decades", file: REL("src/app/layout.tsx") },
  { sheet: "Global", page: "Layout",      field: "SEO description",    value: "A small curation of the automobiles that rewrote their decades: the Countach, the 959, the McLaren F1, the Veyron.", file: REL("src/app/layout.tsx") },
  { sheet: "Global", page: "About page",  field: "About SEO title",       value: "About — The Motor Gallery", file: REL("src/app/about/page.tsx") },
  { sheet: "Global", page: "About page",  field: "About SEO description", value: "About The Motor Gallery and the curation of cars through the decades.", file: REL("src/app/about/page.tsx") },

  // ========= HOMEPAGE — kept on a "Homepage" sheet (separate from Navigation) =========
  { sheet: "Homepage", page: "Hero",      field: "Eyebrow",                value: "A virtual exhibition", file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Headline part 1",        value: "The machines that",   file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Headline part 2",        value: "redrew their decade.", file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Lede paragraph",         value: "A permanent exhibit in four rooms. Each one a portrait of a single\n              automobile and the moment it shifted the language of the supercar.", file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Primary CTA",            value: "Enter the gallery",    file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Secondary CTA",          value: "About the curation",   file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Stat: Exhibits label",   value: "Exhibits",             file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Stat: Exhibits value",   value: "04",                   file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Stat: Decades label",    value: "Decades",              file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Stat: Decades value",    value: "1970s → 2000s",        file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Stat: Artifacts label",  value: "Artifacts",            file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Hero",      field: "Stat: Artifacts value",  value: "69",                   file: REL("src/app/page.tsx") },

  { sheet: "Homepage", page: "Marquee",   field: "Marquee item 1",         value: "1974  Lamborghini Countach", file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Marquee",   field: "Marquee item 2",         value: "1986  Porsche 959",          file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Marquee",   field: "Marquee item 3",         value: "1992  McLaren F1",           file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Marquee",   field: "Marquee item 4",         value: "2005  Bugatti Veyron",       file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Marquee",   field: "Marquee item 5",         value: "Velocity",                   file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Marquee",   field: "Marquee item 6",         value: "Vision",                     file: REL("src/app/page.tsx") },

  { sheet: "Homepage", page: "Featured stack", field: "Eyebrow",        value: "Primary Evidence",                                                                                       file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Featured stack", field: "Headline part 1", value: "Not nostalgia.",                                                                                          file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Featured stack", field: "Headline part 2", value: "The shock of first encounter.",                                                                          file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Featured stack", field: "Lede",           value: "Sixty-nine artifacts, pulled from the original magazine scans,\n              press photographs, and auction catalogues that introduced these\n              cars to the world. Period voices. Period paper. Period dust.", file: REL("src/app/page.tsx") },

  { sheet: "Homepage", page: "Curator's note", field: "Eyebrow",  value: "Curator&apos;s Note", file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Curator's note", field: "Pull line 1", value: "Four automobiles.", file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Curator's note", field: "Pull line 2", value: "Four decades.",     file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Curator's note", field: "Pull accent", value: "One long argument about what a car could be.", file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Curator's note", field: "Body",        value: "We began with the <em>Countach</em>, because everything that followed was\n                in conversation with it. Then the <em>959</em>, which ended the argument\n                about whether computers belonged in sports cars. Then the{\" \"}\n                <em>McLaren F1</em>, which answered the argument by ignoring it. Finally\n                the <em>Veyron</em>, which insisted the argument was never really about\n                speed.", file: REL("src/app/page.tsx") },

  { sheet: "Homepage", page: "Exhibits directory", field: "Eyebrow",  value: "The Exhibits, in order", file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Exhibits directory", field: "Headline", value: "Four rooms.",            file: REL("src/app/page.tsx") },
  { sheet: "Homepage", page: "Exhibits directory", field: "Caption",  value: "Hover a row — the lead artifact swaps into the panel on the right.\n                Click to enter the room.", file: REL("src/app/page.tsx") },

  { sheet: "Homepage", page: "Wordmark",  field: "Tagline",    value: "A small gallery for the automobiles that mattered.", file: REL("src/app/page.tsx") },
];

/** Build per-car rows from cars.ts. The slug determines which sheet they
 *  go to. The map below is the only place where slug → display sheet name
 *  is configured. */
const SLUG_TO_SHEET: Record<string, string> = {
  countach: "Lamborghini",
  "959":    "Porsche",
  f1:       "McLaren",
  veyron:   "Bugatti",
};

function buildCarRows(): ContentRow[] {
  const carsFile = REL("src/lib/cars.ts");
  const rows: ContentRow[] = [];
  for (const car of cars) {
    const sheet = SLUG_TO_SHEET[car.slug];
    if (!sheet) continue;
    const page = `${car.maker} ${car.name}`;
    rows.push({ sheet, page, field: "Car name",   value: car.name,    file: carsFile });
    rows.push({ sheet, page, field: "Car maker",  value: car.maker,   file: carsFile });
    rows.push({ sheet, page, field: "Decade",     value: car.decade,  file: carsFile });
    rows.push({ sheet, page, field: "Tagline",    value: car.tagline, file: carsFile });
    rows.push({ sheet, page, field: "Hero caption", value: car.hero.caption, file: carsFile });
    car.essay.forEach((p, i) =>
      rows.push({ sheet, page, field: `Essay paragraph ${i + 1}`, value: p, file: carsFile })
    );
    car.stats.forEach((s, i) => {
      rows.push({ sheet, page, field: `Stat ${i + 1} label`, value: s.label, file: carsFile });
      rows.push({ sheet, page, field: `Stat ${i + 1} value`, value: s.value, file: carsFile });
    });
  }
  return rows;
}

/** Per-car scroll-scene captions + finale title (auto-generated file). */
function buildSceneRows(): ContentRow[] {
  const file = REL("src/lib/scenes.ts");
  const rows: ContentRow[] = [];
  for (const car of cars) {
    const sheet = SLUG_TO_SHEET[car.slug];
    if (!sheet) continue;
    const scene = scenesBySlug[car.slug];
    if (!scene) continue;
    const page = `${car.maker} ${car.name} — Scroll captions`;
    scene.captions.forEach((cap, i) => {
      rows.push({ sheet, page, field: `Scene caption ${i + 1} eyebrow`, value: cap.eyebrow, file });
      rows.push({ sheet, page, field: `Scene caption ${i + 1} line`,    value: cap.line,    file });
    });
    rows.push({ sheet, page, field: "Scene finale title", value: scene.finaleTitle, file });
  }
  return rows;
}

/** Per-car artifact figures (caption, blurb, alt) + footnotes (auto-gen). */
function buildArtifactRows(): ContentRow[] {
  const file = REL("src/lib/artifacts.ts");
  const rows: ContentRow[] = [];
  for (const car of cars) {
    const sheet = SLUG_TO_SHEET[car.slug];
    if (!sheet) continue;
    const data = artifactsBySlug[car.slug];
    if (!data) continue;

    // Primary source citation (per-car header text)
    const headerPage = `${car.maker} ${car.name} — Artifacts header`;
    rows.push({ sheet, page: headerPage, field: "Primary source citation", value: data.primarySource.citation, file });

    // Each figure
    let sectionTitle = "";
    let figIdx = 1;
    for (const item of data.artifacts) {
      if (item.kind === "section") {
        sectionTitle = item.title;
        const sectionPage = `${car.maker} ${car.name} — Section: ${sectionTitle}`;
        rows.push({ sheet, page: sectionPage, field: "Section title",      value: item.title,     file });
        rows.push({ sheet, page: sectionPage, field: "Section tier label", value: item.tierLabel, file });
        continue;
      }
      const fig = item;
      const page = `${car.maker} ${car.name} — Figure ${fig.figId} (${sectionTitle})`;
      rows.push({ sheet, page, field: `Fig ${fig.figId} blurb`,     value: fig.blurb,    file });
      rows.push({ sheet, page, field: `Fig ${fig.figId} caption`,   value: fig.caption,  file });
      rows.push({ sheet, page, field: `Fig ${fig.figId} alt text`,  value: fig.alt,      file });
      rows.push({ sheet, page, field: `Fig ${fig.figId} footnote`,  value: fig.footnote, file });
      rows.push({ sheet, page, field: `Fig ${fig.figId} filename`,  value: fig.filename, file });
      figIdx++;
    }

    // Footnotes (the consolidated array at the bottom of each car's data)
    data.footnotes.forEach((fn, i) => {
      rows.push({
        sheet,
        page: `${car.maker} ${car.name} — Footnotes`,
        field: `Footnote ${i + 1}`,
        value: fn,
        file,
      });
    });
  }
  return rows;
}

/** Bibliography entries — site-wide, alphabetized by author. */
function buildBibliographyRows(): ContentRow[] {
  const file = REL("src/lib/bibliography.ts");
  return bibliography.map((entry, i) => ({
    sheet: "Bibliography",
    page: "Bibliography",
    field: `Entry ${i + 1}`,
    value: entry,
    file,
  }));
}

/** Image references — these aren't text content, but listing the
 *  filename + its caption helps the user identify which file in
 *  /public/artifacts/<slug>/ corresponds to which figure when
 *  swapping in their own scans. */
function buildImageReferenceRows(): ContentRow[] {
  const rows: ContentRow[] = [];
  for (const car of cars) {
    const data = artifactsBySlug[car.slug];
    if (!data) continue;
    const dir = `public/artifacts/${data.imgDir}/`;
    let sectionTitle = "";
    for (const item of data.artifacts) {
      if (item.kind === "section") {
        sectionTitle = item.title;
        continue;
      }
      const fig = item;
      rows.push({
        sheet: "Images",
        page: `${car.maker} ${car.name}`,
        field: `Fig ${fig.figId} (${sectionTitle}) — file at ${dir}${fig.filename}`,
        value: fig.filename,
        file: REL("src/lib/artifacts.ts"),
      });
    }
  }
  // Per-car hero images from cars.ts
  for (const car of cars) {
    car.images.forEach((img, i) => {
      rows.push({
        sheet: "Images",
        page: `${car.maker} ${car.name} — Hero images`,
        field: `Hero image ${i + 1}`,
        value: img,
        file: REL("src/lib/cars.ts"),
      });
    });
  }
  return rows;
}

export function buildAllRows(): ContentRow[] {
  return [
    ...STATIC_ROWS,
    ...buildCarRows(),
    ...buildSceneRows(),
    ...buildArtifactRows(),
    ...buildBibliographyRows(),
    ...buildImageReferenceRows(),
  ];
}

export const SHEET_ORDER = [
  "Navigation",
  "McLaren",
  "Porsche",
  "Lamborghini",
  "Bugatti",
  "About",
  "Homepage",
  "Bibliography",
  "Images",
  "Global",
];
