/**
 * Upgrade the four bare "Martin Lee, ..." Le Mans 1995 bibliography
 * entries to full Chicago author-date with URLs (pulled from
 * artifacts.ts sourceLink fields). They're distinct photos, so we
 * keep all four — just reformat them.
 *
 *   Run:  npx tsx scripts/upgrade_martin_lee.ts
 *
 * Re-alphabetizes after the rewrite and regenerates CITATIONS.md.
 */

import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { bibliography } from "../src/lib/bibliography.js";

const ROOT = process.cwd();
const BIB_PATH = path.resolve(ROOT, "src/lib/bibliography.ts");
const TS = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);

/** bare-form → full-Chicago replacement table.
 *  URLs are taken verbatim from src/lib/artifacts.ts sourceLink fields. */
const REPLACEMENTS: Record<string, string> = {
  "Martin Lee, 1st/2nd/3rd Place Finishers at Le Mans 1995 Podium, Wikimedia Commons, CC BY-SA 2.0.":
    "Lee, Martin. *1st/2nd/3rd Place Finishers at Le Mans 1995 Podium*. Photograph. 1995. Wikimedia Commons. CC BY-SA 2.0. https://commons.wikimedia.org/wiki/File:The_1st,_2nd_%26_3rd_place_finishers_on_the_podium_at_Le_Mans_1995_(49626653518).jpg.",

  "Martin Lee, 3rd Place McLaren F1 GTR #51 Team on Podium, Le Mans 1995, Wikimedia Commons, CC BY-SA 2.0.":
    "Lee, Martin. *3rd Place McLaren F1 GTR #51 Team on Podium, Le Mans 1995*. Photograph. 1995. Wikimedia Commons. CC BY-SA 2.0. https://commons.wikimedia.org/wiki/File:The_3rd_place_Mclaren_F1_GTR_-51_team_of_Andy_Wallace,_Derek_Bell_%26_Justin_Bell_on_the_podium_at_Le_Mans_1995_(49627171486).jpg.",

  "Martin Lee, Winning McLaren F1 GTR #59 at Ford Chicane, Le Mans 1995, Wikimedia Commons, CC BY-SA 2.0.":
    "Lee, Martin. *Winning McLaren F1 GTR #59 at Ford Chicane, Le Mans 1995*. Photograph. 1995. Wikimedia Commons. CC BY-SA 2.0. https://commons.wikimedia.org/wiki/File:The_wining_Mclaren_F1_GTR_-59_of_Yannick_Dalmas,_Masanori_Sekiya_%26_J.J.Lehto_at_Ford_Chicane_at_Le_Mans_1995_(49627167201).jpg.",

  "Martin Lee, Winning McLaren F1 GTR #59 Team on the Podium at Le Mans 1995, June 11 1995, Wikimedia Commons, CC BY-SA 2.0.":
    "Lee, Martin. *Winning McLaren F1 GTR #59 Team on the Podium at Le Mans 1995*. Photograph. 11 June 1995. Wikimedia Commons. CC BY-SA 2.0. https://commons.wikimedia.org/wiki/File:The_wining_Mclaren_F1_GTR_-59_team_of_Yannick_Dalmas,_Masanori_Sekiya_%26_J.J.Lehto_on_the_podium_at_Le_Mans_1995_(49627444137).jpg.",
};

let upgraded = 0;
let unmatched: string[] = [];
const next = bibliography.map((entry) => {
  const replacement = REPLACEMENTS[entry];
  if (replacement) {
    upgraded++;
    return replacement;
  }
  return entry;
});
for (const k of Object.keys(REPLACEMENTS)) {
  if (!bibliography.includes(k)) unmatched.push(k);
}

// Re-alphabetize. Sort key = first comma- or period-bounded chunk.
function sortKey(entry: string): string {
  const stripped = entry.replace(/\*([^*]+)\*/g, "$1").trim();
  const firstChunk = stripped.split(/[,.]/)[0] || stripped;
  return firstChunk.toLowerCase();
}
next.sort((a, b) => sortKey(a).localeCompare(sortKey(b)));

const header = `// AUTO-GENERATED by _build_nextjs_data.py.
// Bibliography, deduplicated by scripts/dedup_bibliography.ts and the
// Martin Lee Le Mans 1995 entries upgraded to full Chicago with URLs by
// scripts/upgrade_martin_lee.ts. Re-alphabetized by author surname.
// Re-running the Python build will regenerate from scratch and wipe
// these edits.

export const bibliography: string[] = [
`;
const body = next.map((e) => `  ${JSON.stringify(e)},`).join("\n");
const out = `${header}${body}\n];\n`;

const original = fs.readFileSync(BIB_PATH, "utf8");
fs.writeFileSync(`${BIB_PATH}.backup.${TS}`, original, "utf8");
fs.writeFileSync(BIB_PATH, out, "utf8");

console.log(`Upgraded ${upgraded}/${Object.keys(REPLACEMENTS).length} Martin Lee entries.`);
if (unmatched.length) {
  console.log(`⚠  Could not find these bare entries (already changed?):`);
  for (const u of unmatched) console.log(`    ${u}`);
}
console.log(`Bibliography re-alphabetized; ${next.length} entries total.`);

// Try to regenerate CITATIONS.md (write to .new.md if locked)
const result = spawnSync("npx", ["tsx", "scripts/build_citations.ts"], {
  cwd: ROOT,
  stdio: "inherit",
  shell: true,
});
if (result.status !== 0) {
  console.warn(
    `\n⚠  CITATIONS.md regeneration failed (probably open in editor). Run manually after closing it: npx tsx scripts/build_citations.ts`
  );
}

console.log(`\nBackup: src/lib/bibliography.ts.backup.${TS}`);
